[task.test]
command = "go test -fullpath ./..."
description = "Testing the entire project."
depends = [
    "format"
]

[task.format]
command = "go fmt ./..."
description = "Format entire codebase"

[task.build]
command = "go build -o hotshot main.go"
description = "Build the project."
depends = [
    "format"
]
