// Code generated by "stringer -type=Op"; DO NOT EDIT.

package code

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RETURN-0]
	_ = x[PUSH-1]
	_ = x[DIV-2]
	_ = x[ADD-3]
	_ = x[MUL-4]
	_ = x[SUB-5]
	_ = x[TRUE-6]
	_ = x[FALSE-7]
}

const _Op_name = "RETURNPUSHDIVADDMULSUBTRUEFALSE"

var _Op_index = [...]uint8{0, 6, 10, 13, 16, 19, 22, 26, 31}

func (i Op) String() string {
	if i < 0 || i >= Op(len(_Op_index)-1) {
		return "Op(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Op_name[_Op_index[i]:_Op_index[i+1]]
}
