// Code generated by "stringer -type=Op"; DO NOT EDIT.

package code

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RETURN-0]
	_ = x[PUSH-1]
	_ = x[DIV-2]
	_ = x[ADD-3]
	_ = x[MUL-4]
	_ = x[SUB-5]
	_ = x[TRUE-6]
	_ = x[FALSE-7]
	_ = x[GT-8]
	_ = x[LT-9]
	_ = x[EQ-10]
	_ = x[JCMP-11]
	_ = x[JMP-12]
	_ = x[SET-13]
	_ = x[GET-14]
	_ = x[JT-15]
}

const _Op_name = "RETURNPUSHDIVADDMULSUBTRUEFALSEGTLTEQJCMPJMPSETGETJT"

var _Op_index = [...]uint8{0, 6, 10, 13, 16, 19, 22, 26, 31, 33, 35, 37, 41, 44, 47, 50, 52}

func (i Op) String() string {
	if i < 0 || i >= Op(len(_Op_index)-1) {
		return "Op(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Op_name[_Op_index[i]:_Op_index[i+1]]
}
